FROM nginx:1.31.3-alpine@sha256:4a73073bd557c65b759505da037898b61f1be6cbcc3c2c3aeac22d2a470c1752

ARG INFRA_COMMIT=unknown
ARG CORE_COMMIT=unknown
ARG DOCUMENTATION_COMMIT=unknown
ARG RELEASE_VERSION=unreleased
ARG BUILD_DATE=unknown
ARG REPOSITORY=unknown
ARG SOURCE_TREE_DIGEST=unknown

LABEL org.opencontainers.image.revision=$INFRA_COMMIT \
      org.opencontainers.image.version=$RELEASE_VERSION \
      org.opencontainers.image.created=$BUILD_DATE \
      org.opencontainers.image.source=$REPOSITORY \
      com.ircenter.core.revision=$CORE_COMMIT \
      com.ircenter.documentation.revision=$DOCUMENTATION_COMMIT \
      com.ircenter.source-tree.sha256=$SOURCE_TREE_DIGEST

COPY docker/nginx/conf.d/ /etc/nginx/conf.d/
COPY docker/health/nginx-healthcheck.sh /usr/local/bin/ircenter-nginx-healthcheck
COPY app/public/ /var/www/html/public/
COPY documentation-app/public/ /var/www/documentation/public/

RUN chmod 0555 /usr/local/bin/ircenter-nginx-healthcheck \
    && find /var/www/html/public /var/www/documentation/public -type d -exec chmod 0555 {} + \
    && find /var/www/html/public /var/www/documentation/public -type f -exec chmod 0444 {} + \
    && printf '{"infra_commit":"%s","core_commit":"%s","documentation_commit":"%s","version":"%s","build_date":"%s"}\n' \
        "$INFRA_COMMIT" "$CORE_COMMIT" "$DOCUMENTATION_COMMIT" "$RELEASE_VERSION" "$BUILD_DATE" \
        > /app-release.json \
    && chmod 0444 /app-release.json
